weapons = {
    "Unarmed": {"WC": (1, 3), "Cost": 0},
    "Spiked Knuckles": {"WC": (1, 5), "Cost": 5},
    "Dagger": {"WC": (3, 7), "Cost": 10},
    "Gladius": {"WC": (5, 9), "Cost": 25},
    "Halberd": {"WC": (7, 11), "Cost": 50},
    "Battle Mace": {"WC": (9, 13), "Cost": 65},
    "Long Sword": {"WC": (11, 15), "Cost": 80},
    "Dwarven Axe": {"WC": (15, 19), "Cost": 100},
    "Broad Sword": {"WC": (17, 21), "Cost": 125},
    "Dragon Lance": {"WC": (20, 25), "Cost": 150},
    "Chaos Blade": {"WC": (40, 50), "Cost": 300},
}

armors = {
    "No Armor": {"AC": 0, "Cost": 0},
    "Linen Cloth": {"AC": 2, "Cost": 5},
    "Sage's Robe": {"AC": 4, "Cost": 10},
    "Leather Armor": {"AC": 6, "Cost": 25},
    "Chain Mail Armor": {"AC": 18, "Cost": 50},
    "Steel Armor": {"AC": 10, "Cost": 65},
    "Mythril Armor": {"AC": 12, "Cost": 80},
    "Diamond Armor": {"AC": 15, "Cost": 100},
    "Adamantine Armor": {"AC": 20, "Cost": 125},
    "Dragon Armor": {"AC": 25, "Cost": 150},
    "Chaos Armor": {"AC": 50, "Cost": 300},
}

potions = {
    "Potion of Nothingness": {"Recover": 0, "Cost": 0},
    "Health Potion I": {"Recover": 10, "Cost": 10},
    "Health Potion II": {"Recover": 25, "Cost": 25},
    "Health Potion III": {"Recover": 50, "Cost": 40},
}

monsters = {
    "Slime": {
        "HP": 125,
        "Strength": 14,
        "Defense": 14,
        "Dexterity": 14,
        "Weapon": "Unarmed",
        "Armor": "No Armor",
        "Gold": [1, 5],
        "Floor": 1,
    },
    "Goblin": {
        "HP": 100,
        "Strength": 12,
        "Defense": 12,
        "Dexterity": 15,
        "Weapon": "Dagger",
        "Armor": "Linen Cloth",
        "Gold": [5, 10],
        "Floor": 2,
    },
    "Leprechaun": {
        "HP": 100,
        "Strength": 14,
        "Defense": 14,
        "Dexterity": 14,
        "Weapon": "Dagger",
        "Armor": "Linen Cloth",
        "Gold": [10, 50],
        "Floor": 3,
    },
    "Skeleton": {
        "HP": 125,
        "Strength": 12,
        "Defense": 12,
        "Dexterity": 14,
        "Weapon": "Gladius",
        "Armor": "Leather Armor",
        "Gold": [10, 15],
        "Floor": 4,
    },
    "Lizardman": {
        "HP": 125,
        "Strength": 12,
        "Defense": 12,
        "Dexterity": 15,
        "Weapon": "Halberd",
        "Armor": "Leather Armor",
        "Gold": [15, 20],
        "Floor": 5,
    },
    "HellHound": {
        "HP": 125,
        "Strength": 20,
        "Defense": 17,
        "Dexterity": 18,
        "Weapon": "Unarmed",
        "Armor": "No Armor",
        "Gold": [20, 25],
        "Floor": 6,
    },
    "WereWolf": {
        "HP": 175,
        "Strength": 22,
        "Defense": 20,
        "Dexterity": 18,
        "Weapon": "Unarmed",
        "Armor": "No Armor",
        "Gold": [25, 30],
        "Floor": 8,
    },
    "Troll": {
        "HP": 225,
        "Strength": 12,
        "Defense": 20,
        "Dexterity": 14,
        "Weapon": "Battle Mace",
        "Armor": "Linen Cloth",
        "Gold": [30, 35],
        "Floor": 7,
    },
    "Orc": {
        "HP": 175,
        "Strength": 22,
        "Defense": 18,
        "Dexterity": 15,
        "Weapon": "Battle Mace",
        "Armor": "Linen Cloth",
        "Gold": [35, 40],
        "Floor": 9,
    },
    "WereBear": {
        "HP": 175,
        "Strength": 27,
        "Defense": 27,
        "Dexterity": 14,
        "Weapon": "Unarmed",
        "Armor": "No Armor",
        "Gold": [40, 45],
        "Floor": 10,
    },
    "Two-Horned Ogre": {
        "HP": 175,
        "Strength": 17,
        "Defense": 17,
        "Dexterity": 15,
        "Weapon": "Long Sword",
        "Armor": "Chain Mail Armor",
        "Gold": [45, 50],
        "Floor": 11,
    },
    "Gargoyle": {
        "HP": 225,
        "Strength": 32,
        "Defense": 32,
        "Dexterity": 18,
        "Weapon": "Unarmed",
        "Armor": "No Armor",
        "Gold": [50, 60],
        "Floor": 12,
    },
    "Minotaur": {
        "HP": 200,
        "Strength": 22,
        "Defense": 17,
        "Dexterity": 15,
        "Weapon": "Dwarven Axe",
        "Armor": "Chain Mail Armor",
        "Gold": [60, 70],
        "Floor": 13,
    },
    "Headless Knight": {
        "HP": 175,
        "Strength": 22,
        "Defense": 17,
        "Dexterity": 20,
        "Weapon": "Broad Sword",
        "Armor": "Adamantine Armor",
        "Gold": [70, 80],
        "Floor": 14,
    },
    "Dragon King": {
        "HP": 300,
        "Strength": 50,
        "Defense": 50,
        "Dexterity": 30,
        "Weapon": "Unarmed",
        "Armor": "No Armor",
        "Gold": [80, 100],
        "Floor": 15,
    },
    "Prince of Hell - Azazel": {
        "HP": 250,
        "Strength": 60,
        "Defense": 40,
        "Dexterity": 50,
        "Weapon": "Dragon Lance",
        "Armor": "Dragon Armor",
        "Gold": [0, 1],
        "Floor": 16,
    },
}
